# MSH-TESTER-2021.09

RESET="\033[0m"
BLACK="\033[30m"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
MAGENTA="\033[35m"
CYAN="\033[36m"
WHITE="\033[37m"

BOLDBLACK="\033[1m\033[30m"
BOLDRED="\033[1m\033[31m"
BOLDGREEN="\033[1m\033[32m"
BOLDYELLOW="\033[1m\033[33m"
BOLDBLUE="\033[1m\033[34m"
BOLDMAGENTA="\033[1m\033[35m"
BOLDCYAN="\033[1m\033[36m"
BOLDWHITE="\033[1m\033[37m"

# Compile and set executable rights
make -C ../ > /dev/null
cp ../minishell .
chmod 755 minishell


GOOD=0
TOTAL=0

pipe=/tmp/testpipe
trap "rm -f $pipe" EXIT
if [[ ! -p $pipe ]]; then
    mkfifo $pipe
fi

function exec_test()
{
  
  rm -f msh_log
  # execute commands, separated by ';' in minishell, using nfifo
  ./minishell <$pipe >msh_log 2>&- &
  mshpid=$!
  IFS=';' read -ra CMND <<< "$@"
  for command in "${CMND[@]}"; do
    echo $command > $pipe
  done

  # only leaks mode
  if [ $LEAKSMODE  ]; then
    echo "leaks $mshpid | grep 'leaks for' | grep -v ' 0 leaks' >> leaks" > $pipe
    echo 'exit' > $pipe 
    sleep 0.03
    wait $!
    sleep 0.03
    if [[ $(cat leaks 2>&-) != "" ]]; then
      printf "\n$BOLDRED LEAKS! $YELLOW%s$RESET\n" "$@"
      rm -f leaks
    else
      printf "$BOLDGREEN%s$RESET" "✓ "
    fi
    return
  fi

  echo 'exit' > $pipe 
  sleep 0.03
  wait $!
  ES_1=$?
  TEST1=$(cat msh_log)

  rm -f msh_log
  # execute commands in bash
  bash -posix < $pipe >msh_log 2>&-  &
  IFS=';' read -ra CMND <<< "$@"
  for command in "${CMND[@]}"; do
    echo $command > $pipe
  done
  echo 'exit' > $pipe
  wait $!
  ES_2=$?
  TEST2=$(cat msh_log)

  # compare result
  if [ "$TEST1" == "$TEST2" ] && [ "$ES_1" == "$ES_2" ]; then
    printf "$BOLDGREEN%s$RESET" "✓ "
    ((GOOD++))
  else
    printf "\n$BOLDRED%s$RESET" "✗ "
    printf "$CYAN \"$@\" $RESET"
  fi
  if [ "$TEST1" != "$TEST2" ]; then
    echo
    printf $BOLDRED"Your output : \n%.20s\n$BOLDRED$TEST1\n%.20s$RESET\n" "-----------------------------------------" "-----------------------------------------"
    printf $BOLDGREEN"Expected output : \n%.20s\n$BOLDGREEN$TEST2\n%.20s$RESET\n" "-----------------------------------------" "-----------------------------------------"
    echo
  fi
  if [ "$ES_1" != "$ES_2" ]; then
    echo
    printf $BOLDRED"Your exit status : $BOLDRED$ES_1$RESET\n"
    printf $BOLDGREEN"Expected exit status : $BOLDGREEN$ES_2$RESET\n"
    echo
  fi
  ((TOTAL++))
  sleep 0.03
}

if [ "$1" == "" ] || [ "$1" == "help" ]; then
  printf "$BOLDMAGENTA\n\tAvailable arg: \n$YELLOW\tall$RESET echo cd pipe env export redirect multi syntax exit\n\
      $GREEN\tbonus$RESET quote wildcard oper\n"
fi
if [ "$1" == "all" ]; then
  printf "$BOLDMAGENTA    _____ _ _ _____ _____ _ _ ______ _ _ \n"
  printf "| \/ |_ _| \ | |_ _|/ ____| | | | ____| | | | \n"
  printf "| \ / | | | | \| | | | | (___ | || | |  | | | | \n"
  printf "| |\/| | | | | . \` | | | \___ \|   | | | | | | \n"
  printf "| | | |_| |_| |\ |_| |_ ____) | | | | |____| |____| |____ \n"
  printf "|_| |_|_____|_| \_|_____|_____/|_| |_|______|______|______|\n$RESET"
fi

if [ "$2" == "leaks" ]; then
  printf $BOLDBLUE"\n\tONLY LEAKS MODE\n"$RESET
  LEAKSMODE=1
  rm -f leaks
fi

# PARSING
if [ "$1" == "parsing" ] || [ "$1" == "all" ]; then
  printf $BOLDMAGENTA"\n\tPARSING\n"$RESET
  exec_test 'echo "\s"'
  exec_test 'echo "bip | bip && coyotte > < "'
  exec_test 'echo $USER$var$USER$USER$USERtest$USER user42$USERuser42$USERtestuser42'
  exec_test 'echo $USER$var$USER$USER$USERtest$USER'
  exec_test '$'
  exec_test '$LESS$VAR'
  exec_test '..'
  exec_test 'echo '"abc"''
  exec_test 'echo "'abc'"'
  exec_test 'echo "" bonjour'
  exec_test 'echo	a'
  exec_test 'export ""  et unset ""'
  exec_test 'export "test=ici"=coucou'
  exec_test 'echo $test'
  exec_test 'export var="cat Makefile | grep >"'
  exec_test 'echo $var'
fi

# ECHO TESTS
if [ "$1" == "echo" ] || [ "$1" == "all" ]; then
  printf $BOLDMAGENTA"\n\tECHO TESTS\n"$RESET
  exec_test 'pwd ; pwd'
  exec_test 'echo test tout'
  exec_test 'echo -n test tout'
  exec_test 'echo -n -n -n test tout'
  exec_test 'echo "'$USER'"'
  exec_test 'echo "''"'
  exec_test 'echo "'$USER'" "" '' $USER $USERr '"$USER"''
  exec_test 'echo $=$=$= $=  $='
  exec_test 'echo $+$+$+  $'
  exec_test 'echo -n'
  exec_test 'echo -nn'
  exec_test 'echo -'
  exec_test 'echo --n'
  exec_test 'echo "-n"'
  exec_test 'echo -n blabla'
  exec_test 'echo -nn blabla'
  exec_test 'echo - blabla'
  exec_test 'echo --n blabla'
  exec_test 'echo "-n" blabla'
  exec_test 'echo -nblabla'
  exec_test 'echo""'
  exec_test 'echo -n""'
  exec_test 'echo hello'
  exec_test 'echo exit'
  exec_test 'echo -n'
  exec_test 'echo'
  exec_test 'echo hello blabla'
  exec_test 'echo -n -n -n blabla'
  exec_test 'echo blabla -n'
  exec_test 'echo echo hello'
  exec_test 'echo "bla"bla ""''"'''" bla"bla   "'   "  ""  'sdc" ssdsd " sd' s''d s'sd 's'sd ' s' "vd v'd 'v df 'd df' v' dfv' dv' df 'dvf ' df vdf    v'df v' df'v "'
  exec_test 'echo echo'
  exec_test 'eCho '
  exec_test 'eChO'
  exec_test 'eCHO'
  exec_test 'ECHO'
  exec_test 'echo rhobebou'
  exec_test 'echo stop barking'
  exec_test 'echo "bonjour"'
  exec_test 'echo bonjour'
  exec_test 'echo 'bonjour''
  exec_test 'echo -n bonjour'
  exec_test 'echo -nn bonjour'
  exec_test 'echo -n -n -n bonjour'
  exec_test 'echo -n -n -n bonjour'
  exec_test 'echo "-n" bonjour'
  exec_test 'echo -n"-n" bonjour'
  exec_test 'echo "-nnnn" bonjour'
  exec_test 'echo "-n -n -n"-n bonjour'
  exec_test 'echo "-n '-n'" bonjour'
  exec_test 'echo $USER'
  exec_test 'echo "$USER"'
  exec_test 'echo "'$USER'"'
  exec_test 'echo " '$USER' "'
  exec_test 'echo text"$USER"'
  exec_test 'echo text"'$USER'" ' $USER ''
  exec_test 'echo "text"   "$USER"    "$USER"'
  exec_test 'echo '              $USER          ''
  exec_test 'echo               text "$USER"            "$USER"text'
  exec_test 'echo ''''''''''$USER'''''''''''
  exec_test 'echo """"""""$USER""""""""'
  exec_test 'echo $USER'$USER'text oui oui     oui  oui $USER oui      $USER '''
  exec_test 'echo $USER '' $USER $USER '' $USER '' $USER -n $USER'
  exec_test 'echo "$USER""$USER""$USER"'
  exec_test 'echo text"$USER"test'
  exec_test 'echo '$USER' "$USER" "text text"'
  exec_test 'echo '$USER''
  exec_test 'echo $USER " "'
  exec_test 'echo "$USER""Users/$USER/file""'$USER'"'$USER''
  exec_test 'echo "$USER$USER$USER"'
  exec_test 'echo '$USER'"$USER"'$USER''
  exec_test 'echo '"$USER"''$USER'"""$USER"'
  exec_test 'echo " $USER  "'$PWD''
  exec_test 'echo " $USER  $ "'$PWD''
  exec_test 'echo $USER=4'
  exec_test 'echo $USER=thallard'
  exec_test 'echo $USER'
  exec_test 'echo $USER213'
  exec_test 'echo $USER$12USER$USER=4$USER12'
  exec_test 'echo $USER $123456789USER $USER123456789'
  exec_test 'echo $USER $9999USER $8888USER $7777USER'
  exec_test 'echo $USER $USER9999 $USER8888 $USER7777'
  exec_test 'echo $USER $USER9999 $USER8888 $USER7777 "$USER"'
  exec_test 'echo "$USER=12$USER"'
  exec_test 'echo "$9USER" "'$USER=12$SOMETHING'"'
  exec_test 'echo $PWD/file'
  exec_test 'echo "$PWD/file"'
  exec_test 'echo "text" "text$USER" ... "$USER"'
  exec_test 'echo $PWD'
  exec_test 'echo -n -n -nnnn -nnnnm 	-nnnnm'
  exec_test 'echo -n -nnn hello -n 	hello -n'
  exec_test 'echo poil | cat -e	poil$'
fi

# CD TESTS
if [ "$1" == "cd" ] || [ "$1" == "all" ]; then
  printf $BOLDMAGENTA"\n\tCD TESTS\n"$RESET
  exec_test 'cd .. ; pwd'
  exec_test 'cd /Users ; pwd'
  exec_test 'cd ; pwd'
  exec_test 'cd . ; pwd'
  exec_test 'mkdir test_dir ; cd test_dir ; rm -rf ../test_dir ; cd . ; cd .. ; pwd'
  exec_test 'cd .a ; pwd'
  exec_test 'cd ; pwd'
  exec_test 'cd .. ; pwd'
  exec_test 'cd . ; pwd'
  exec_test 'cd /Users ; pwd'
  exec_test 'cd // ; pwd'
  exec_test 'cd ////// ; pwd'
  exec_test 'cd ./././ ; pwd'
  exec_test 'cd / ; pwd'
  exec_test 'cd '/etc' ; pwd'
  exec_test 'cd '/var' ; pwd'
  exec_test 'cd "$OLDPWD" ; pwd'
  exec_test 'cd "doesntexist" ; pwd'
  exec_test 'cd "doesntexist">/dev/null ; pwd'
  exec_test 'cd ../../.. ; pwd'
  exec_test 'cd "wtf" >/dev/null ; pwd'
  exec_test 'cd ../../../../../../../../../../../../../../.. ; pwd'
  exec_test 'cd .. ; pwd'
  exec_test 'cd ? ; pwd'
  exec_test 'cd + ; pwd'
  exec_test 'cd _ ; pwd'
  exec_test 'cd woof ; pwd'
  exec_test 'cd bark bark ; pwd'
  exec_test 'cd '/' ; pwd'
  exec_test 'cd $OLDPWD ; pwd'
  exec_test 'cd $OLDPWD/.. ; pwd'
  exec_test 'cd ../../../../../.. ; pwd' 
  exec_test 'cd /home/user42/ ; pwd'
  exec_test 'cd too many arguments ; pwd'
  exec_test 'cd ./ ; pwd'
  exec_test 'cd a/b ; pwd'
  exec_test 'cd .. ; pwd'
  exec_test 'cd home/.. ; pwd'
fi

# PIPE TESTS
if [ "$1" == "pipe" ] || [ "$1" == "all" ]; then
  printf $BOLDMAGENTA"\n\tPIPE TESTS\n"$RESET
  exec_test '/bin/ls'
	exec_test 'cat tests/lorem.txt | grep arcu | cat -e'
	exec_test 'echo test | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e| cat -e| cat -e| cat -e| cat -e| cat -e| cat -e| cat -e| cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat -e'
#	exec_test 'cat /dev/random | head -c 100 | wc -c'
	exec_test 'ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls'
	exec_test 'ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls'
  head -c 2000000 /dev/zero > big_file
  exec_test ' cat big_file | ls'
  exec_test ' cat big_file | echo lol'
  exec_test 'echo test | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e| cat -e| cat -e| cat -e| cat -e| cat -e| cat -e| cat -e| cat -e|cat -e|cat -e|cat -e|cat -e|cat -e|cat'
  exec_test 'cat /dev/urandom | head -c 100 | wc -c'
  exec_test 'ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls'
  exec_test 'cat Makefile | grep pr | head -n 5 | cd file_not_exit'
  exec_test 'cat Makefile | grep pr | head -n 5 | hello'
  exec_test 'ls | exit'
  exec_test 'sleep 0.1 | exit'
fi

# ENV EXPANSIONS
if [ "$1" == "env" ] || [ "$1" == "all" ]; then
  printf $BOLDMAGENTA"\n\tENV EXPANSIONS TESTS\n"$RESET
	exec_test 'echo test test'
	exec_test 'echo test'
	exec_test 'echo $TEST'
	exec_test 'echo "$TEST"'
	exec_test 'echo '$TEST''
	exec_test 'echo "$TEST$TEST$TEST"'
	exec_test 'echo "$TEST$TEST=lol$TEST"'
	exec_test 'echo " $TEST lol $TEST"'
	exec_test 'echo $TEST$TEST$TEST'
	exec_test 'echo $TEST$TEST=lol$TEST""lol'
	exec_test 'echo $TEST lol $TEST'
	exec_test 'echo test "$TEST" test "$TEST " test'
	exec_test 'echo "$=TEST"'
	exec_test 'echo "$"'
	exec_test 'echo "$?TEST"'
	exec_test 'echo $TEST $TEST'
	exec_test 'echo "$1TEST"'
	exec_test 'echo "$T1TEST"'
  exec_test 'export TEST=BLA ; echo "test"'
  exec_test 'export TEST=BLA ; echo $TEST'
  exec_test 'export TEST=BLA ; echo "$TEST"'
  exec_test 'export TEST=BLA ; echo '$TEST''
  exec_test 'export TEST=BLA ; echo "$TEST$TEST$TEST"'
  exec_test 'export TEST=BLA ; echo "$TEST$TEST=lol$TEST"'
  exec_test 'export TEST=BLA ; echo "   $TEST lol $TEST"'
  exec_test 'export TEST=BLA ; echo $TEST$TEST$TEST'
  exec_test 'export TEST=BLA ; echo $TEST$TEST=lol$TEST""lol'
  exec_test 'export TEST=BLA ; echo    $TEST lol $TEST'
  exec_test 'export TEST=BLA ; echo test "" test "" test'
  exec_test 'export TEST=BLA ; echo "$TEST"'
  exec_test 'export TEST=BLA ; echo "$=TEST"'
  exec_test 'export TEST=BLA ; echo "$ "'
  exec_test 'export TEST=BLA ; echo "$ f"'
  exec_test 'export TEST=BLA ; echo " $ "'
  exec_test 'export TEST=BLA ; echo " $ $USER"'
  exec_test 'export TEST=BLA ; echo ""$ '
  exec_test 'export TEST=BLA ; echo $"" '
  exec_test 'export TEST=BLA ; echo $'' '
  exec_test 'export TEST=BLA ; echo X'"$"""''
  exec_test 'export TEST=BLA ; echo "$?TEST"'
  exec_test 'export TEST=BLA ; echo $TEST $TEST'
  exec_test 'export TEST=BLA ; echo "$1TEST"'
  exec_test 'export TEST=BLA ; echo "$T1TEST"'
  exec_test 'export CHEVRON=">" ; echo bla $CHEVRON yo ; ls'
  exec_test 'echo " $" ; echo "$" ; echo "$""" ; echo "$"XX"" ; echo X"$"""'
  exec_test 'echo $'
  exec_test 'echo " $ "'
  exec_test 'echo " $? "'
  exec_test 'echo $''?$""$' '$" "$'?'$"?"$'? '$"? "" $ "" $? "'
  exec_test 'echo $'USER''
  exec_test 'echo $"USER"'
  exec_test 'echo $'USER ''
  exec_test 'echo $"USER "'
  exec_test 'echo " $ "'
  exec_test 'echo " $USER "'
  exec_test 'echo $'USERR''
  exec_test 'echo $"USERR"'
  exec_test 'echo $'USERR ''
  exec_test 'echo $"USERR "'
  exec_test 'echo " $ "'
  exec_test 'echo " $USERR "'
  exec_test 'echo $''?$""$' '$" "$'USER'$"USER"$'USER '$"USER "" $ "" $USER "'
  exec_test 'echo $?$?$?$?$?$?$?$'
  exec_test 'echo $'USER''
  exec_test 'echo $"USER"'
  exec_test 'echo '$USER''
  exec_test 'echo "$USER"'
  exec_test 'echo "'$USER'"'
  exec_test 'echo '"$USER"''
  exec_test 'echo $USER"'"'
  exec_test 'echo $USER""'
  exec_test 'echo ''$USER'
  exec_test 'echo $'USER'$"USER"'$USER'"$USER""'$USER'"'"$USER"'$USER"'"$USER""''$USER'
  exec_test 'echo $?$USER'
  exec_test 'export 'USER'=YO'
  exec_test 'echo $'USER''
  exec_test 'echo $'''
  exec_test 'echo $""'
  exec_test 'echo $' ''
  exec_test 'echo $" "'
  exec_test 'echo $'?''
  exec_test 'echo $"?"'
  exec_test 'echo $'? ''
  exec_test 'echo $"? "'
  exec_test 'echo " $"USER'
  exec_test 'export var="truc" ; echo $var'
  exec_test 'export var="truc" ; echo $var | cat -e'
  exec_test 'echo "$tests""Makefile"'
  exec_test 'echo "$tests"Makefile'
  exec_test 'echo "$tests" "Makefile"'
  exec_test '$bla'
  exec_test 'export var="truc" ; echo $var bonjour ; export $var'
  exec_test 'export test=123'
  exec_test 'export var= s -la ; l$var'
  exec_test 'export var=at ; c$var Makefile'
  exec_test 'export loop='bonjour$loop' ; echo $loop'
fi

# EXPORT
if [ "$1" == "export" ] || [ "$1" == "all" ]; then
  printf $BOLDMAGENTA"\n\tEXPORT TESTS\n"$RESET
  ENV_SHOW="env | sort | grep -v SHLVL | grep -v _="
  EXPORT_SHOW="export | sort | grep -v SHLVL | grep -v _= | grep -v OLDPWD"
  exec_test 'export ='
  exec_test "export 1TEST= ; $ENV_SHOW"
  exec_test "export TEST ; $EXPORT_SHOW"
  exec_test "export ""="" ; $ENV_SHOW"
  exec_test "export TES=T="" ; $ENV_SHOW"
  exec_test "export TE+S=T="" ; $ENV_SHOW"
  exec_test "export TEST=LOL ; echo $TEST ; $ENV_SHOW"
  exec_test "export TEST=LOL ; echo $TEST$TEST$TEST=lol$TEST"
  exec_test "export TEST1=LOL TEST2=PIKAPIKA ; echo $TEST ; $ENV_SHOW"
  exec_test "export TEST1=LOL TEST2 $ENV_SHOW"
  exec_test "export TEST=LOL ; unset TEST $ENV_SHOW"
  exec_test "export TEST=LOL ; export TEST+=LOL ; echo $TEST ; $ENV_SHOW"
  exec_test $ENV_SHOW
  exec_test $EXPORT_SHOW
  exec_test "export TEST="ls -l - a" ; echo $TEST ; $ENV_SHOW"
  exec_test 'export TEST=BLA ; echo test        test'
  exec_test 'unset _ ; env | sort'
  exec_test 'export TESTFCGFCSGFC ; env | sort'
  exec_test 'export TESTNBKJNLJ='rferfh$ref' ; env | sort'
  exec_test 'export TESTNBKJNLJdgf="'rferfh$ref'" ; env | sort'
  exec_test 'export TESTNBKJNLJtcfgvhjbk="rferfh$ref" ; env | sort'
  exec_test 'export = ; env | sort'
  exec_test 'export 1TESTHBGUHBUHB= ; env | sort'
  exec_test 'export TESTOUHOSIOUNXJKNK 34khh -deded ; env | sort'
  exec_test 'export ""="" ; env | sort'
  exec_test 'export "=" ; env | sort'
  exec_test 'export TESTFGCHVJKNLJKHVJGCHFGVJBKNL2='' ; env | sort'
  exec_test 'export TESTFGCHVJKNLJKHVJGCHFGVJBKNL3="" ; env | sort'
  exec_test 'export "$" ; env | sort'
  exec_test 'export TESTJHBSJCBJHSC111=T="" ; env | sort'
  exec_test 'export TESTNJNCKJDCKDCKDJN222+S=T="" ; env | sort'
  exec_test 'export TESTKXSLXSLX333=LOL ; env | sort'
  exec_test 'export TESTYGVSBNJKHBXGJHN444=LOL ; env | sort'
  exec_test 'export TESTREDTUHINJO555=LOL ; env | sort'
  exec_test 'export TESTYRFTGUIHUJOKL666=lol ; env | sort'
  exec_test 'export TESTYRFTGUIHUJOKL666=LOLdfgtgh ; env | sort'
  exec_test 'export TESTYTFUGYHIUNJ777="ls       -l     - a" ; env | sort'
  exec_test 'export | grep TEST ; env | sort'
  exec_test 'export arg='"hello"' ; env | sort'
  exec_test 'export TESTFGCHVJKNLJKHVJGCHFGVJBKNL4="$" ; env | sort'
  exec_test 'export TESTrsxydtcfyvgubhnijomkonjbhiugv=bla ; export TESTtdcvhbknlm="YO" ; export TESTjknmlmklnj='kuhkuhk' ; export TESTjkndfv='"kuhku"hk' ; export TESTjkndfvnj='"ku$?hku"hk' ; export | grep TEST ; unset TESTtdcvhbknlm | unset TESTjknmlmklnj ; export | grep TEST ; unset TESTtdcvhbknlm | TESTjknmlmklnj ; export | grep TEST ; unset   TESTjkndfv='"kuhku"hk' ; export | grep TEST ; unset   _TESTjkndfv= ; export | grep TEST ; unset   __TESTjkndfv= ; export | grep TEST ; unset 0 ; export | grep TEST ; unset   567890RFUYGVHBK | unset 65798uhjnk ; export | grep TEST ; unset       "TESTrsxydtcfyvgubhnijomkonjbhiugv" ; export | grep TEST'
  exec_test 'unset PATH ; echo $PATH ; ls ; unset "" test ; unset = ; unset PWD ; echo "END"'
  exec_test 'echo $test ; export test="  foo    bar  " ; echo $test ; export test="  foo    bar  " ; echo ab$test ; export test="  foo    bar  " ; echo "ab"$test ; export test=" foo   bar " ; echo ab"$test" | cat -e ; export test=" foo   bar " ; echo "$test" ; export test=" foo   bar " ; echo ""$test"" ; export test=" foo   bar " ; echo """$test"""'
  exec_test 'export _TEST=tewfqq ; export'

fi

# REDIRECTIONS
if [ "$1" == "redirect" ] || [ "$1" == "all" ]; then
  printf $BOLDMAGENTA"\n\tREDIRECTION TESTS\n"$RESET
  exec_test 'echo test > ls ; cat ls'
  exec_test 'echo test > ls >> ls >> ls ; echo test >> ls ; cat ls'
  exec_test '> lol echo test lol ; cat lol'
  exec_test '>lol echo > test>lol>test>>lol>test mdr >lol test >test ; cat test'
  exec_test 'cat < ls'
  exec_test 'rm -f ls ; cat > ls < ls ; rm -f ls'
  exec_test 'ls > ls'
  exec_test 'cat <ls'
  exec_test 'pwd >pwd ; cat pwd'
  exec_test 'pwd >pwd ; cat pwd | echo'
  exec_test 'cat | <Makefile cat ; hello'
  exec_test 'cat <test.sh <ls'
  exec_test 'cat << stop ; 1 ; stop'
  exec_test 'cat << stop ; 1OF ; stopa ; stop'
  exec_test 'cat <test.sh <<stop ; 1 ; stop'
  exec_test 'cat <<stop<ls ; 1 ; stop'
  exec_test 'cat <test.sh << stop1 <<stop2 ; a ; b ; c ; stop1 ; run2 ; stop2'
  exec_test 'rm -f ls >ls'
  exec_test 'echo jhjbsdc >> tmp1 ; cat tmp1 ; ls ; cat tmp1 ; rm tmp1'
  exec_test 'echo kjnsdc sdc sddc > tmp1 knsdc sdc  sdcsdc > tmp1 ; cat tmp1 ; ls ; cat tmp1 ; rm tmp1'
  exec_test 'cat < tester.sh < jnsdc ssdjcnnj > tmp2 ; ls ; cat tmp2 ; rm tmp2'
  exec_test 'cat tmp2 ; cat < tester.sh > tmp2 ; ls ; cat tmp2 ; rm tmp2'
  exec_test 'cat<tester.sh<jnsdc ssdjcnnj>tmp2 ; ls ; cat tmp2 ; rm tmp2'
  exec_test 'ls >tmp1 > tmp1 ; cat tmp1 ; rm tmp1'
  exec_test 'ls >tmp1 >> tmp1 >>tmp1 ; cat tmp1 ; rm tmp1'
  exec_test 'ls >tmp1 > tmp1 <tmp1 ; cat tmp1 ; rm tmp1'
  exec_test 'echo hello > tmp1 ; cat tmp1 ; rm tmp1'
  exec_test 'ls >tmp1 >> tmp1 >>tmp1 | cat ; rm tmp1'
  exec_test 'echo hello > tmp1 ; echo hhell >> tmp1 ; cat tmp1 ; rm tmp1'
  exec_test 'echo hello >> tmp1 | echo bla ; cat tmp1 ; rm tmp1'
  exec_test 'echo hello >> tmp1 | echobla ; cat tmp1 ; rm tmp1'
  exec_test 'echobla | echo hello >> tmp1 ; cat tmp1 ; rm tmp1'
  exec_test 'cat << '$USER' > tmp1 ; ; cat tmp1 ; rm tmp1'
  exec_test 'cat << $USER > tmp1 ; cat tmp1 ; rm tmp1'
  exec_test 'cat << $AAAAAAAA > tmp1 ; cat tmp1 ; rm tmp1'
  exec_test 'cat << "hello'ksdcksd'ckdsc'""""""'"kjbsdckj'"fddvdf"vdfvdfv'bsdc > tmp1 ; cat tmp1 ; rm tmp1'
  exec_test 'cat << "b$" > tmp1 ; cat tmp1 ; rm tmp1'
  exec_test '<a cat <b <c ; <a cat <b <c ; > test1 | echo blabla ; cat hello > test1 ; >test1 cat <test2 >>test3 ; >a ls <machin >>c >d ; ls ; >test1 ; cat test1 ; rm test1 test2 test3 d a'
fi


# MULTI TESTS
if [ "$1" == "multi" ] || [ "$1" == "all" ]; then
  printf $BOLDMAGENTA"\n\tMULTI TESTS\n"$RESET
  exec_test 'echo testing multi >lol ; echo <lol <lola ; echo "test 1  | and 2" >>lol ; cat <lol ; cat ../Makefile <lol | grep minishell'
  exec_test 'unset PATH ; /bin/ls'
  exec_test 'unset PATH ; ./Makefile'
  exec_test 'echo 5 > ls ; <5 cat ; rm 5'
  exec_test 'ls | echo 6 > ls ; <6 cat ; rm 6'
  exec_test 'cd ; unset HOME ; cd'
  exec_test 'cd .. > 1 ; pwd'
  exec_test 'cd .. > 1| pwd'
  exec_test 'pwd > 1'
  exec_test 'pwd > 1 ; cat 1'
  exec_test 'pwd > 1 ; pwd'
  exec_test 'pwd > 1| pwd'
  exec_test 'pwd ; unset HOME ; pwd ; cd ; pwd'
  exec_test 'ls | export TEST=5 ; echo $TEST'
  exec_test 'export TEST1=LOL TEST2=PIKAPIKA ; unset TEST1 TEST2 ; echo $TEST1 ; echo $TEST2'
  exec_test '< tmp1 | > tmp1 ; ls ; rm tmp1'
  exec_test '< $SAMEYEE > tmp1 ; ls ; rm tmp1'
  exec_test 'echo hello > tmp1 ; cat < tmp1 | cat < tmp2 ; ls ; /bin/lsa ; rm tmp1'
  exec_test 'cat < tester.sh | cat < bla | echo hello > tmp2 ; cat tmp2 ; ls ; bla ; rm tmp2 ; chmod 000 tmp2 ; cat tester.sh >> tmp1 > tmp2 > tmp3 | cat tester.sh > tmp1 > tmp3 ; ls ; cat tmp3 ; rm tmp1 tmp2 tmp3'
  exec_test 'echo oui | cat -e ; echo oui | echo non | echo something | grep oui ; echo oui | echo non | echo something | grep non ; echo oui | echo non | echo something | grep something ; cd .. | echo "something" ; cd .. | echo "something" ; cd / | echo "something" ; cd .. | pwd'
  exec_test 'ifconfig | grep ":"'
  exec_test 'ifconfig | grep nothing'
  exec_test 'whoami | grep $USER ; cat tmp1 ; rm tmp1'
  exec_test 'whoami | grep $USER > tmp1 ; cat tmp1 ; rm tmp1'
  exec_test 'whoami | cat -e | cat -e > tmp1 ; cat tmp1 ; rm tmp1'
  exec_test 'whoami | grep "$USER'c'" > tmp1 ; cat tmp1 ; rm tmp1'
  exec_test 'whoami | grep "$USER''" > tmp1 ; cat tmp1 ; rm tmp1'
  exec_test 'export TEST=123 | cat -e | cat -e ; unset TEST | cat -e ; echo test | cat -e | cat -e | cat -e'
  exec_test 'whereis ls | cat -e | cat -e > tmp2 ; cat tmp2 ; rm tmp2'
  exec_test 'echo test | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e'
  exec_test 'ls  | grep "."'
  exec_test 'whereis grep > tmp1 ; whereis grep > tmp2 ; cat tmp1 ; cat tmp2 ; ls  > tmp1 ; ls  < tmp1 ; cat tmp1 ; unset PATH ; ls | ls | ls ; rm tmp1 ; rm tmp2'
  exec_test 'echo bla | exit'
  exec_test 'echo bla | exit khbsdk'
  exec_test 'cat < notexist | exit 42'
  exec_test 'exit 42 | cat < notexist'
  exec_test 'exit tamere | exit'
  exec_test 'exit | exit  1| exit 200'
  exec_test '> test1 echo bla ; >> test1 echo bla ; > test1 << pwd ; bla ; pwd ; cat test1 ; rm test1'
  exec_test 'cd random_cmd'
  exec_test 'cd random_cmd'
  exec_test 'cd $?'
  exec_test './file_that_is_not_an_executable'
  exec_test 'cat bla	1'
  exec_test 'file_name'
  exec_test 'not_cmd'
  exec_test 'ls bonjour'
  exec_test 'export test=a'
  exec_test 'echo $test'
#  exec_test '<test1 | <test2'
fi

# SYNTAX 
if [ "$1" == "syntax" ] || [ "$1" == "all" ]; then
  printf $BOLDMAGENTA"\n\tSYNTAX\n"$RESET
  exec_test ''
  exec_test '" echo" lol'
  exec_test '"echo " lol'
  exec_test '" echo" | " pwd"'
  exec_test '"echo " | "pwd "'
  exec_test '/bin/lsa'
  exec_test './Makefile'
  exec_test '| test'
  exec_test 'echo > <'
  exec_test 'echo | |'
  exec_test 'echo "||"'
  exec_test '<'
  exec_test 'rm -f ls ; cat < ls > ls'
  exec_test 'grep -z'
  exec_test 'ls"| "wc -l'
  exec_test '/ls'
fi

# SIGNALS
if [ "$1" == "signal" ] || [ "$1" == "all" ]; then
  printf $BOLDMAGENTA"\n\tSIGNALS\n"$RESET
  exec_test 'kill -INT 888'
  exec_test 'echo hello | kill -INT 888'
fi

# EXIT
if [ "$1" == "exit" ] || [ "$1" == "all" ]; then
  printf $BOLDMAGENTA"\n\tEXIT\n"$RESET
  exec_test 'exit 42'
  exec_test 'exit 42 53 68'
  exec_test 'exit 259'
  exec_test 'exit 9223372036854775807'
  exec_test 'exit -9223372036854775808'
  exec_test 'exit 9223372036854775806'
  exec_test 'exit -9223372036854775807'
  exec_test 'exit 9223372036854775808'
  exec_test 'exit 9223372036854775809'
  exec_test 'exit -9223372036854775809'
  exec_test 'exit -9223372036854775810'
  exec_test 'exit 9223372037754775807'
  exec_test 'exit -9223372037754775808'
  exec_test 'exit 99999999999999999999999'
  exec_test 'exit -99999999999999999999999'
  exec_test 'exit -4'
  exec_test 'exit wrong'
  exec_test 'exit  2 wrong_command'
  exec_test 'gdagadgag'
  exec_test 'ls -Z'
  exec_test 'cd gdhahahad'
  exec_test 'ls -la | wtf'
  exec_test 'exit 0 0'
  exec_test 'exit 42 42'
  exec_test 'exit -42 -24'
  exec_test 'exit 42'
  exec_test 'exit 42 53 68'
  exec_test 'exit 259'
  exec_test 'exit -12030'
  exec_test 'exit --1239312'
  exec_test 'exit ++++1203020103'
  exec_test 'exit +0'
  exec_test 'exit ++++++0'
  exec_test 'exit -----0'
  exec_test 'exit azerty'
  exec_test 'exit kewkwqke'
  exec_test 'exit a'
  exec_test 'exit z'
  exec_test 'exit "1"'
  exec_test 'exit "2"'
  exec_test 'exit "+102"'
  exec_test 'exit "1230"'
  exec_test 'exit "+++1230"'
  exec_test 'exit "1"23'
  exec_test 'exit "2"32"32"'
  exec_test 'exit "'42'"'
  exec_test 'exit '42'"42"42'
  exec_test 'exit +'42'"42"42'
  exec_test 'exit -'42'"42"42'
  exec_test 'exit 9223372036854775807'
  exec_test 'exit 9223372036854775808'
  exec_test 'exit 9223372036854775806'
  exec_test 'exit 9223372036854775809'
  exec_test 'exit -9223372036854775807'
  exec_test 'exit -9223372036854775808'
  exec_test 'exit -9223372036854775806'
  exec_test 'exit -9223372036854775809'
  exec_test 'exit -4'
  exec_test 'exit wrong'
  exec_test 'exit wrong_command'
  exec_test 'exit something'
  exec_test 'exit 1'
  exec_test 'exit -1'
  exec_test 'exit 42'
  exec_test 'exit 0'
  exec_test 'exit --000'
  exec_test 'exit +++++++000'
  exec_test 'exit ++++3193912939'
  exec_test 'exit ---31232103012'
  exec_test 'exit "something"'
  exec_test 'exit q'
  exec_test 'exit help'
  exec_test 'exit export'
  exec_test 'exit echo'
  exec_test 'exit cd ..'
  exec_test 'exit 0 0'
  exec_test 'exit something somethingv2'
  exec_test 'exit 42 42 42 42 42'
  exec_test 'exit echo something'
  exec_test 'exit exit'
 fi

if [ "$1" == "sheet" ]; then
  printf $BOLDMAGENTA"\n\tSHEET TESTS\n"$RESET
  exec_test ' >'
  exec_test ' <'
  exec_test ' >>'
  exec_test ' <<'
  exec_test ' <>'
  exec_test ' >>>>>'
  exec_test ' >>>>>>>>>>>>>>>'
  exec_test ' <<<<<'
  exec_test ' <<<<<<<<<<<<<<<<'
  exec_test ' > > > >'
  exec_test ' >> >> >> >>'
  exec_test ' >>>> >> >> >>'
#  exec_test ' /'
  exec_test ' //'
  exec_test ' /.'
  exec_test ' /./../../../../..'
  exec_test ' ///////'
  exec_test ' -'
  exec_test ' |'
  exec_test ' | hola'
  exec_test ' | | |'
  exec_test ' ||'
  exec_test ' |||||'
  exec_test ' |||||||||||||'
  exec_test ' >>|><'
  exec_test ' &&'
  exec_test ' &&&&&'
  exec_test ' &&&&&&&&&&&&&&'
  exec_test ' ;;'
  exec_test ' ;;;;;'
  exec_test ' ;;;;;;;;;;;;;;;'
  exec_test ' ()'
  exec_test ' ( ( ) )'
  exec_test ' ( ( ( ( ) ) ) )'
  exec_test ' ""'
  exec_test ' "hola"'
  exec_test ' 'hola''
  exec_test ' '''
  exec_test ' *'
  exec_test ' */*'
  exec_test ' */*'
#  exec_test ' .'
  exec_test ' ..'
#  exec_test ' ~'
  exec_test ' hola'
  exec_test ' hola que tal'
  exec_test ' Makefile'
  exec_test ' echo'
  exec_test ' echo -n'
  exec_test ' echo Hola'
  exec_test ' echoHola'
  exec_test ' echo-nHola'
  exec_test ' echo -n Hola'
  exec_test ' echo "-n" Hola'
  exec_test ' echo -nHola'
  exec_test ' echo Hola -n'
  exec_test ' echo Hola Que Tal'
  exec_test ' echo         Hola'
  exec_test ' echo    Hola     Que    Tal'
  exec_test ' echo       hola'
  exec_test ' echo "         " | cat -e'
  exec_test ' echo           | cat -e'
  exec_test ' ""''echo hola""'''' que""'' tal""'''
  exec_test ' echo -n -n'
  exec_test ' echo -n -n Hola Que'
  exec_test ' echo -p'
  exec_test ' echo -nnnnn'
  exec_test ' echo -n -nnn -nnnn'
  exec_test ' echo -n-nnn -nnnn'
  exec_test ' echo -n -nnn hola -nnnn'
  exec_test ' echo -n -nnn-nnnn'
  exec_test ' echo --------n'
  exec_test ' echo -nnn --------n'
  exec_test ' echo -nnn -----nn---nnnn'
  exec_test ' echo -nnn --------nnnn'
  exec_test ' echo $'
  exec_test ' echo $?'
  exec_test ' echo $?$'
  exec_test ' echo $? | echo $? | echo $?'
  exec_test ' echo $:$= | cat -e'
  exec_test ' echo " $ " | cat -e'
  exec_test ' echo ' $ ' | cat -e'
  exec_test ' echo $HOME'
  exec_test ' echo $HOME9'
  exec_test ' echo $HOME%'
  exec_test ' echo Le path de mon HOME est $HOME'
  exec_test ' echo $hola'
  exec_test ' echo -nnnn $hola'
  exec_test ' echo > <'
  exec_test ' echo | |'
  exec_test ' EechoE'
  exec_test ' .echo.'
  exec_test ' >echo>'
  exec_test ' <echo<'
  exec_test ' >>echo>>'
  exec_test ' |echo|'
  exec_test ' |echo -n hola'
  exec_test ' echo *'
  exec_test ' echo '*''
  exec_test ' echo D*'
  exec_test ' echo *Z'
  exec_test ' echo *t hola'
  exec_test ' echo *t'
  exec_test ' echo $*'
  exec_test ' echo hola*hola *'
  exec_test ' echo $hola*'
  exec_test ' echo $""'
  exec_test ' echo "$"""'
  exec_test ' echo '$''''
  exec_test ' echo $"HOME"'
  exec_test ' echo $''HOME'
  exec_test ' echo $""HOME'
  exec_test ' echo "$HO"ME'
  exec_test ' echo '$HO'ME'
  exec_test ' echo "$HO""ME"'
  exec_test ' echo '$HO''ME''
  exec_test ' echo "'$HO''ME'"'
  exec_test ' echo ""$HOME'
  exec_test ' echo ''$HOME'
  exec_test ' echo $"HO""ME"'
  exec_test ' echo $'HO''ME''
  exec_test ' echo $'HOME''
  exec_test ' echo "$"HOME'
  exec_test ' echo $"HOLA"'
  exec_test ' echo $'HOLA''
  exec_test ' echo $DONTEXIST Hola'
  exec_test ' echo "hola"'
  exec_test ' echo 'hola''
  exec_test ' echo ''hola'''
  exec_test ' echo ''h'o'la'''
  exec_test ' echo "''h'o'la''"'
  exec_test ' echo "'"h'o'la"'"'
  exec_test ' echo"'hola'"'
  exec_test ' echo "'hola'"'
  exec_test ' echo '"hola"''
  exec_test ' echo '''ho"''''l"a''''
  exec_test ' echo hola""""""""""""'
  exec_test ' echo hola"''''''''''"'
  exec_test ' echo hola'''''''''''''
  exec_test ' echo hola'""""""""""''
  exec_test ' e"cho hola"'
  exec_test ' e'cho hola''
  exec_test ' echo "hola     " | cat -e'
  exec_test ' echo ""hola'
  exec_test ' echo "" hola'
  exec_test ' echo ""             hola'
  exec_test ' echo ""hola'
  exec_test ' echo "" hola'
  exec_test ' echo hola""bonjour'
  exec_test ' "e"'c'ho 'b'"o"nj"o"'u'r'
  exec_test ' "e"'c'ho 'b'"o"nj"o"'u'r'
  exec_test ' echo "$DONTEXIST"Makefile'
  exec_test ' echo "$DONTEXIST""Makefile"'
  exec_test ' echo "$DONTEXIST" "Makefile"'
  exec_test ' $?'
  exec_test ' $?$?'
  exec_test ' ?$HOME'
  exec_test ' $'
  exec_test ' $HOME'
  exec_test ' $DONTEXIST'
  exec_test ' $LESS$VAR'
 # exec_test ' env hola | sort'
 # exec_test ' env hola que tal | sort'
  exec_test ' env env | sort'
  exec_test ' env env env env env | sort'
 # exec_test ' env ls | sort'
  exec_test 'export HOLA=bonjour ; env | sort'
  exec_test 'export       HOLA=bonjour ; env | sort'
  exec_test 'export Hola ; export'
  exec_test 'export Hola9hey ; export'
#  exec_test ' export $DONTEXIST'
  exec_test ' export | grep "HOME'
  exec_test ' export ='
  exec_test ' export %'
  exec_test ' export $?'
  exec_test ' export 9HOLA='
  exec_test 'export HOLA9=bonjour ; env | sort'
  exec_test 'export _HOLA=bonjour ; env | sort'
  exec_test 'export ___HOLA=bonjour ; env | sort'
  exec_test 'export _HO_LA_=bonjour ; env | sort'
  exec_test ' export HOL@=bonjour'
#  exec_test ' export -HOLA=bonjour'
#  exec_test ' export --HOLA=bonjour'
  exec_test ' export HOLA-=bonjour'
  exec_test ' export HO-LA=bonjour'
  exec_test ' export HOL.A=bonjour'
  exec_test ' export HOL}A=bonjour'
  exec_test ' export HOL{A=bonjour'
  exec_test ' export HO*LA=bonjour'
  exec_test ' export HO#LA=bonjour'
  exec_test ' export HO@LA=bonjour'
  exec_test ' export HO$?LA=bonjour ; env | sort'
  exec_test ' export +HOLA=bonjour'
  exec_test ' export HOL+A=bonjour'
  exec_test ' export HOLA+=bonjour ; env | sort'
  exec_test ' export HOLA=bonjour ; export HOLA+=bonjour ; env | sort'
  exec_test ' exportHOLA=bonjour ; env | sort'
  exec_test ' export HOLA =bonjour'
  exec_test ' export HOLA = bonjour'
  exec_test ' export HOLA=bon jour ; env | sort'
  exec_test ' export HOLA= bonjour ; env | sort'
  exec_test ' export HOLA=bonsoir ; export HOLA=bonretour ; export HOLA=bonjour ; env | sort'
  exec_test ' export HOLA=$HOME ; env | sort'
  exec_test ' export HOLA=bonjour$HOME ; env | sort'
  exec_test ' export HOLA=$HOMEbonjour ; env | sort'
  exec_test ' export HOLA=bon$jour ; env | sort'
  exec_test ' export HOLA=bon(jour'
  exec_test ' export HOLA=bon()jour'
  exec_test ' export HOLA=bon@jour ; env | sort'
  exec_test ' export HOLA=bon;jour ; env | sort'
  exec_test ' export HOLA=bon""jour"" ; env | sort'
  exec_test ' export HOLA=bonjour=casse-toi ; echo $HOLA'
  exec_test ' export ""HOLA=bonjour""=casse-toi ; echo $HOLA'
  exec_test ' export HOLA=bonjour ; export BYE=casse-toi ; echo $HOLA et $BYE'
  exec_test ' export HOLA=bonjour BYE=casse-toi ; echo $HOLA et $BYE'
  exec_test ' export $HOLA=bonjour'
  exec_test ' export HOLA=""bonjour      ""   ; echo $HOLA | cat -e'
  exec_test ' export HOLA=""   -n bonjour   ""   ; echo $HOLA'
  exec_test ' export HOLA=""bonjour   ""/ ; echo $HOLA'
  exec_test ' export "'
  exec_test ' export HOLA='""' ; echo "" $HOLA "" | cat -e'
  exec_test ' export HOLA=at ; c$HOLA Makefile'
  exec_test ' export """" HOLA=bonjour ; env | sort'
  exec_test ' export HOLA=""cat Makefile | grep NAME""   ; echo $HOLA'
  exec_test ' export HOLA=hey  ; echo $HOLA$HOLA$HOLA=hey$HOLA'
  exec_test ' export HOLA=""  bonjour  hey  ""   ; echo $HOLA | cat -e'
  exec_test ' export HOLA=""  bonjour  hey  ""   ; echo """"""$HOLA"""""" | cat -e'
  exec_test ' export HOLA=""  bonjour  hey  ""   ; echo wesh""$HOLA"" | cat -e'
  exec_test ' export HOLA=""  bonjour  hey  ""   ; echo wesh""""$HOLA.'
  exec_test ' export HOLA=""  bonjour  hey  ""   ; echo wesh$""""HOLA.'
  exec_test ' export HOLA=""  bonjour  hey  ""   ; echo wesh$""HOLA HOLA"".'
  exec_test ' export HOLA=bonjour ; export HOLA="" hola et $HOLA"" ; echo $HOLA'
  exec_test ' export HOLA=bonjour ; export HOLA=' hola et $HOLA' ; echo $HOLA'
  exec_test ' export HOLA=bonjour ; export HOLA="" hola et $HOLA""$HOLA ; echo $HOLA'
  exec_test ' export HOLA=""ls        -l    - a"" ; echo $HOLA'
  exec_test ' export HOLA=""s -la""  ; l$HOLA'
  exec_test ' export HOLA=""s -la""  ; l""$HOLA""'
  exec_test ' export HOLA=""s -la""  ; l'$HOLA''
  exec_test ' export HOLA=""l""  ; $HOLAs'
  exec_test ' export HOLA=""l""  ; ""$HOLA""s'
  exec_test ' export HOL=A=bonjour ; env | sort'
  exec_test ' export HOLA=""l""  ; '$HOLA's'
  exec_test ' export HOL=A="""" ; env | sort'
  exec_test ' export HOL=A=""'
  exec_test ' export ""=""'
  exec_test ' export ''='''
  exec_test ' export "="="="'
  exec_test ' export '='='=''
  exec_test ' export HOLA=p ; export BYE=w ; $HOLA""BYE""d'
  exec_test ' export HOLA=p ; export BYE=w ; ""$HOLA""'$BYE'd'
  exec_test ' export HOLA=p ; export BYE=w ; ""$HOLA""""$BYE""d'
  exec_test ' export HOLA=p ; export BYE=w ; $""HOLA""$""BYE""d'
  exec_test ' export HOLA=p ; export BYE=w ; $'HOLA'$'BYE'd'
  exec_test ' export HOLA=-n ; ""echo $HOLA"" hey'
  exec_test ' export A=1 B=2 C=3 D=4 E=5 F=6 G=7 H=8 ; echo ""$A$B""$C""$D$E""$F""$G$H""'
  #exec_test ' export HOLA=bonjour ; env | sort ; unset HOLA=bonjour ; env | sort'
  #exec_test ' export HOLA=bonjour ; env | sort ; unset HOLA=bonjour ; unset HOLA=bonjour ; env | sort'
  exec_test ' unset PATH ; echo $PATH'
  exec_test ' unset PATH ; ls'
  exec_test ' unset ""'
  exec_test ' unset INEXISTANT'
  #exec_test ' unset PWD ; env | grep PWD ; pwd'
  exec_test ' pwd ; unset PWD ; env | sort | grep PWD ; cd $PWD ; pwd'
  exec_test ' unset OLDPWD ; env | sort | grep OLDPWD'
  exec_test ' unset 9HOLA'
  exec_test ' unset HOLA9'
  exec_test ' unset HOL?A'
  exec_test ' unset HOLA='
  exec_test ' unset HOL;A'
  exec_test ' unset HOL.A'
  exec_test ' unset HOL+A'
  exec_test ' unset HOL=A'
  exec_test ' unset HOL{A'
  exec_test ' unset HOL}A'
  exec_test ' unset HOL-A'
  #exec_test ' unset -HOLA'
  exec_test ' unset _HOLA'
  exec_test ' unset HOL_A'
  exec_test ' unset HOLA_'
  exec_test ' unset HOL*A'
  exec_test ' unset HOL#A'
  exec_test ' unset $HOLA'
  exec_test ' unset $PWD'
  exec_test ' unset HOL@'
  exec_test ' unset HOL^A'
  exec_test ' unset HOL$?A'
  exec_test ' unset """" HOLA ; env | grep HOLA'
  exec_test ' unset PATH ; echo $PATH'
  exec_test ' unset PATH ; cat Makefile'
  exec_test ' unset ='
  exec_test ' unset ======'
  exec_test ' unset ++++++'
  exec_test ' unset _______'
  exec_test ' unset export'
  exec_test ' unset echo'
  exec_test ' unset pwd'
  exec_test ' unset cd'
  exec_test ' unset unset'
  exec_test ' unset sudo'
  exec_test ' export hola | unset hola | echo $?'
  exec_test ' /bin/echo'
  exec_test ' /bin/echo Hola Que Tal'
  #exec_test ' /bin/env | sort'
  exec_test ' /bin/cd Desktop'
 # exec_test ' history'
  exec_test ' pwd'
  exec_test ' pwd hola'
  exec_test ' pwd ./hola'
  exec_test ' pwd hola que tal'
  exec_test ' pwd -p'
  exec_test ' pwd pwd pwd'
  exec_test ' pwd ls'
  exec_test ' pwd ls env | sort'
  exec_test ' cd'
  exec_test ' cd .'
  exec_test ' cd ./'
  exec_test ' cd ./././.'
  exec_test ' cd ././././'
  exec_test ' cd ..'
  exec_test ' cd ../'
  exec_test ' cd ../..'
  exec_test ' cd ../.'
  exec_test ' cd .././././.'
  exec_test ' cd srcs'
  exec_test ' cd srcs objs'
  exec_test ' cd 'srcs''
  exec_test ' cd "srcs"'
  exec_test ' cd '/etc''
  exec_test ' cd /e'tc''
  exec_test ' cd /e"tc"'
  exec_test ' cd sr'
  exec_test ' cd ../minishell'
  exec_test ' cd ../../../../../../..'
  exec_test ' cd .././../.././../bin/ls'
  exec_test ' cd /'
  exec_test ' cd '/''
  exec_test ' cd // ; pwd'
  exec_test ' cd '//' ; pwd'
  exec_test ' cd /// ; pwd'
  exec_test ' cd //////// ; pwd'
  exec_test ' cd '////////' ; pwd'
  exec_test ' cd /minishell'
  exec_test ' cd / ; cd ..'
  exec_test ' cd _'
  #exec_test ' cd -'
  #exec_test ' cd --'
  #exec_test ' cd ---'
  exec_test ' cd $HOME'
  exec_test ' cd $HOME $HOME'
  exec_test ' cd $HOME/42_works'
  exec_test ' cd "$PWD/srcs'
  exec_test ' cd '$PWD/srcs''
  exec_test ' unset HOME ; cd $HOME'
  exec_test ' unset HOME ; export HOME= ; cd'
  exec_test ' unset HOME ; export HOME ; cd'
  exec_test ' cd minishell Docs crashtest.c'
  exec_test '    cd / | echo $? ; pwd'
  exec_test ' cd ~/'
  exec_test ' cd ~/ | echo $? ; pwd'
  exec_test ' cd *'
  exec_test ' cd *'
  exec_test ' cd *'
  exec_test ' mkdir a ; mkdir a/b ; cd a/b ; rm -r ../../a ; cd ..'
  exec_test ' mkdir a ; mkdir a/b ; cd a/b ; rm -r ../../a ; pwd'
  exec_test ' mkdir a ; mkdir a/b ; cd a/b ; rm -r ../../a ; echo $PWD ; echo $OLDPWD'
  exec_test ' mkdir a ; mkdir a/b ; cd a/b ; rm -r ../../a ; cd ; echo $PWD ; echo $OLDPWD'
  exec_test ' mkdir a ; cd a ; rm -r ../a ; echo $PWD ; echo $OLDPWD'
  exec_test ' export CDPATH=/ ; cd $HOME/..'
  exec_test ' export CDPATH=/ ; cd home/vietdu91'
  exec_test ' export CDPATH=./ ; cd .'
  exec_test ' export CDPATH=./ ; cd ..'
  exec_test ' chmod 000 minishell ; ./minishell'
  exec_test ' ls hola'
  exec_test ' ./Makefile'
  exec_test ' ./minishell'
  exec_test ' env | grep SHLVL ; ./minishell ; env | grep SHLVL ; exit ; env | grep SHLVL'
  exec_test ' touch hola ; ./hola'
  exec_test ' exit'
  exec_test ' exit exit'
  exec_test ' exit hola'
  exec_test ' exit hola que tal'
  exec_test ' exit 42'
  exec_test ' exit 000042'
  exec_test ' exit 666'
  exec_test ' exit 666 666'
  exec_test ' exit 666 666'
  exec_test ' exit 666 666'
  exec_test ' exit 666 666 666 666'
  exec_test ' exit 666 hola 666'
  exec_test ' exit hola 666 666'
  exec_test ' exit 259'
  exec_test ' exit -4'
  exec_test ' exit -42'
  exec_test ' exit -0000042'
  exec_test ' exit -259'
  exec_test ' exit -666'
  exec_test ' exit +666'
  exec_test ' exit 0'
  exec_test ' exit +0'
  exec_test ' exit +42'
  exec_test ' exit -69 -96'
  exec_test ' exit --666'
  exec_test ' exit ++++666'
  exec_test ' exit ++++++0'
  exec_test ' exit ------0'
  exec_test ' exit "666"'
  exec_test ' exit '666''
  exec_test ' exit '-666''
  exec_test ' exit '+666''
  exec_test ' exit '----666''
  exec_test ' exit '++++666''
  exec_test ' exit '6'66'
  exec_test ' exit '2'66'32''
  exec_test ' exit "'666'"'
  exec_test ' exit '"666"''
  exec_test ' exit '666'"666"666'
  exec_test ' exit +'666'"666"666'
  exec_test ' exit -'666'"666"666'
  exec_test ' exit 9223372036854775807'
  exec_test ' exit 9223372036854775808'
  exec_test ' exit -9223372036854775808'
  exec_test ' exit -9223372036854775809'
  exec_test ' cat | cat | cat | ls'
  exec_test ' ls | exit'
  exec_test ' ls | exit 42'
  exec_test ' exit | ls'
  exec_test ' echo hola > bonjour ; exit | cat -e bonjour'
  exec_test ' echo hola > bonjour ; cat -e bonjour | exit'
  exec_test ' echo | echo'
  exec_test ' echo hola | echo que tal'
  exec_test ' pwd | echo hola'
  exec_test ' env | echo hola'
  exec_test ' echo oui | cat -e'
  exec_test ' echo oui | echo non | echo hola | grep oui'
  exec_test ' echo oui | echo non | echo hola | grep non'
  exec_test ' echo oui | echo non | echo hola | grep hola'
  exec_test ' echo hola | cat -e | cat -e | cat -e'
  exec_test ' cd .. | echo "hola'
  exec_test ' cd / | echo "hola'
  exec_test ' cd .. | pwd'
  exec_test ' ifconfig | grep ":'
  exec_test ' ifconfig | grep hola'
  exec_test ' whoami | grep $USER'
  exec_test ' whoami | grep $USER > /tmp/bonjour ; cat /tmp/bonjour'
  exec_test ' whoami | cat -e | cat -e > /tmp/bonjour ; cat /tmp/bonjour'
  exec_test ' whereis ls | cat -e | cat -e > /tmp/bonjour ; cat /tmp/bonjour'
  exec_test ' ls | hola'
  exec_test ' ls | ls hola'
  exec_test ' ls | ls | hola'
  exec_test ' ls | hola | ls'
  exec_test ' ls | ls | hola | rev'
  exec_test ' ls | ls | echo hola | rev'
  exec_test ' ls -la | grep "."'
  exec_test ' ls -la | grep "'.'"'
  exec_test ' echo test.c | cat -e| cat -e| cat -e| cat -e| cat -e| cat -e| cat -e| cat -e|cat -e|cat -e|cat -e'
  exec_test '" ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls'
  exec_test '|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls|ls"'
  exec_test ' echo hola | cat | cat | cat | cat | cat | grep hola'
  exec_test ' echo hola | cat'
  exec_test ' echo hola| cat'
  exec_test ' echo hola |cat'
  exec_test ' echo hola|cat'
  exec_test ' echo hola || cat'
  exec_test ' echo hola ||| cat'
  exec_test ' ech|o hola | cat'
  exec_test ' cat Makefile | cat -e | cat -e'
  exec_test ' cat Makefile | grep srcs | cat -e'
  exec_test ' cat Makefile | grep srcs | grep srcs | cat -e'
  exec_test ' cat Makefile | grep pr | head -n 5 | cd file_not_exist'
  exec_test ' cat Makefile | grep pr | head -n 5 | hello'
  exec_test ' export HOLA=bonjour | cat -e | cat -e'
  exec_test ' unset HOLA | cat -e'
  exec_test '" export HOLA | echo hola ; env | grep PROUT"'
  exec_test ' export | echo hola'
  exec_test ' sleep 3 | sleep 3'
  exec_test ' sleep 3 | exit'
  exec_test ' exit | sleep 3'
  exec_test '" echo hola > a ; >>b echo que tal ; cat a | <b cat | cat > c | cat"'
  exec_test ' pwd && ls'
  exec_test ' pwd || ls'
  exec_test ' echo hola || echo bonjour'
  exec_test ' echo hola && echo bonjour'
  exec_test ' echo bonjour || echo hola'
  exec_test ' echo bonjour && echo hola'
  exec_test ' echo -n bonjour && echo -n hola'
  exec_test ' pwd && ls && echo hola'
  exec_test ' pwd || ls && echo hola'
  exec_test ' pwd && ls || echo hola'
  exec_test ' pwd || ls || echo hola'
  exec_test ' ls || export ""'
  exec_test ' export "" || ls'
  exec_test ' ls && export ""'
  exec_test ' export "" && ls'
  exec_test ' ls || ;'
  exec_test ' ; || ls'
  exec_test ' ls && ;'
  exec_test ' ; && ls'
  exec_test ' ls || <'
  exec_test ' ls && <'
  exec_test ' cat | echo || ls'
  exec_test ' cat | echo && ls'
  exec_test ' ls || cat | echo'
  exec_test ' ls && cat | echo'
  exec_test ' export "" && unset ""'
  exec_test ' (ls)'
  exec_test ' ( ( ls ) )'
  exec_test ' ( ( ) ls )'
  exec_test ' ls && (ls)'
  exec_test ' (ls && pwd)'
  exec_test ' ( ( ls&&pwd ) )'
  exec_test ' ( ( ls ) &&pwd )'
  exec_test ' (ls && ( ( pwd ) ) )'
  exec_test ' (ls && pwd) > hola ; cat hola'
  exec_test ' > hola ls && pwd'
  exec_test ' > hola (ls && pwd)'
  exec_test ' (> pwd) ; ls'
  exec_test ' (< pwd) ; ls'
  exec_test ' (< pwd)'
  exec_test ' ( ( ( ( ( pwd) ) ) ) )'
  exec_test ' () pwd'
  exec_test ' > pwd (ls)'
  exec_test ' (ls||pwd)&&(ls||pwd)'
  exec_test ' (lss||pwd)&&(lss||pwd)'
  exec_test ' (lss&&pwd)&&(lss&&pwd)'
  exec_test ' (ls && pwd | wc) > hola ; cat hola'
  exec_test ' (ls && pwd | wc) > hola ; (ls && pwd | wc) > hola ; cat hola'
  exec_test ' (ls && pwd | wc) >> hola ; echo hey&&(ls && pwd | wc) > hola ; cat hola'
  exec_test ' (pwd | wc) < hola'
  exec_test ' (ls && pwd | wc) < hola'
  exec_test ' (ls -z || pwd | wc) < hola'
  exec_test ' echo hey > hola ; (pwd | wc) < hola'
  exec_test ' echo hey > hola ; (ls && pwd | wc) < hola'
  exec_test ' echo hey > hola ; (ls -z || pwd | wc) < hola'
  exec_test ' (ls -z || pwd && ls)'
  exec_test ' ls || (cat Makefile|grep srcs) && (pwd|wc)'
  exec_test ' ls -z && (ls) && (pwd)'
  exec_test ' (ls > Docs/hey && pwd) > hola ; cat hola ; cat Docs/hey'
  exec_test ' ls > Docs/hey && pwd > hola ; cat hola ; cat Docs/hey'
  exec_test ' cd ../.. && pwd && pwd'
  exec_test ' (cd ../.. && pwd) && pwd'
  exec_test ' ls -z || cd ../../..&&pwd ; pwd'
  exec_test ' ls -z || (cd ../../..&&pwd) ; pwd'
  exec_test ' echo hola > bonjour ; cat bonjour'
  exec_test ' echo que tal >> bonjour ; cat bonjour'
  exec_test ' echo hola > bonjour ; echo que tal >> bonjour ; cat < bonjour'
  exec_test ' echo hola > bonjour ; rm bonjour ; echo que tal >> bonjour ; cat < bonjour'
  exec_test ' echo hola que tal > bonjour ; cat bonjour'
  exec_test ' echo hola que tal > /tmp/bonjour ; cat -e /tmp/bonjour'
  exec_test ' export HOLA=hey ; echo bonjour > $HOLA ; echo $HOLA'
  exec_test ' whereis grep > Docs/bonjour ; cat Docs/bonjour'
  exec_test ' ls -la > Docs/bonjour ; cat Docs/bonjour'
  exec_test ' pwd>bonjour ; cat bonjour'
  exec_test ' pwd >                     bonjour ; cat bonjour'
  exec_test ' echo hola > > bonjour'
  exec_test ' echo hola < < bonjour'
  exec_test ' echo hola >>> bonjour'
  exec_test ' > bonjour echo hola ; cat bonjour'
  exec_test ' > bonjour | echo hola ; cat bonjour'
  exec_test ' prout hola > bonjour ; ls'
  exec_test ' echo hola > hello >> hello >> hello ; ls ; cat hello'
  exec_test ' echo hola > hello >> hello >> hello ; echo hola >> hello ; cat < hello'
  exec_test ' echo hola > hello >> hello >> hello ; echo hola >> hello ; echo hola > hello >> hello >> hello ; cat < hello'
  exec_test ' echo hola >> hello >> hello > hello ; echo hola >> hello ; cat < hello'
  exec_test ' echo hola >> hello >> hello > hello ; echo hola >> hello ; echo hola >> hello >> hello > hello ; cat < hello'
  exec_test ' echo hola > hello ; echo hola >> hello >> hello >> hello ; echo hola >> hello ; cat < hello'
  exec_test ' echo hola > hello ; echo hey > bonjour ; echo <bonjour <hello'
  exec_test ' echo hola > hello ; echo hey > bonjour ; echo <hello <bonjour'
  exec_test ' echo hola > bonjour ; echo hey > hello ; rm bonjour hello ; echo hola > bonjour > hello > bonjour ; cat bonjour ; cat hello'
  exec_test ' echo hola > bonjour ; echo hey > hello ; echo hola > bonjour > hello > bonjour ; cat bonjour ; cat hello'
  exec_test ' echo hola > bonjour ; echo hey > hello ; rm bonjour hello ; echo hola > bonjour >> hello > bonjour ; cat bonjour ; cat hello'
  exec_test ' echo hola > bonjour ; echo hey > hello ; echo hola > bonjour > hello > bonjour ; cat bonjour ; cat hello'
  exec_test ' echo hola > bonjour ; echo hey > hello ; rm bonjour hello ; echo hola > bonjour > hello >> bonjour ; cat bonjour ; cat hello'
  exec_test ' echo hola > bonjour ; echo hey > hello ; echo hola > bonjour > hello >> bonjour ; cat bonjour ; cat hello'
  exec_test ' echo hola > bonjour ; echo hey > hello ; rm bonjour hello ; echo hola >> bonjour > hello > bonjour ; cat bonjour ; cat hello'
  exec_test ' echo hola > bonjour ; echo hey > hello ; echo hola >> bonjour > hello > bonjour ; cat bonjour ; cat hello'
  exec_test ' echo hola > bonjour ; echo hey > hello ; rm bonjour hello ; echo hola >> bonjour >> hello >> bonjour ; cat bonjour ; cat hello'
  exec_test ' echo hola > bonjour ; echo hey > hello ; echo hola >> bonjour >> hello >> bonjour ; cat bonjour ; cat hello'
  exec_test ' > bonjour echo hola bonjour ; cat bonjour'
  exec_test ' >bonjour echo > hola>bonjour>hola>>bonjour>hola hey >bonjour hola >hola ; cat bonjour ; cat hola'
  exec_test ' echo bonjour > hola1 ; echo hello > hola2 ; echo 2 >hola1 >> hola2 ; ls ; cat hola1 ; cat hola2'
  exec_test ' echo bonjour > hola1 ; echo hello > hola2 ; echo 2 >>hola1 > hola2 ; ls ; cat hola1 ; cat hola2'
  exec_test ' > pwd ; ls'
  exec_test ' < pwd'
  exec_test ' cat <pwd'
  exec_test ' cat <srcs/pwd'
  exec_test ' cat <../pwd'
  exec_test ' cat >>'
  exec_test ' cat >>>'
  exec_test ' cat >> <<'
  exec_test ' cat >> > >> << >>'
  exec_test ' cat < ls'
  exec_test ' cat < ls > ls'
  exec_test ' cat > ls1 < ls2 ; ls'
  exec_test ' >>hola ; cat hola'
  exec_test ' echo hola > bonjour ; cat < bonjour'
  exec_test ' echo hola >bonjour ; cat <bonjour'
  exec_test ' echo hola>bonjour ; cat<bonjour'
  exec_test ' echo hola> bonjour ; cat< bonjour'
  exec_test ' echo hola               >bonjour ; cat<                     bonjour'
  exec_test ' echo hola          >     bonjour ; cat            <         bonjour'
  exec_test ' echo hola > srcs/bonjour ; cat < srcs/bonjour'
  exec_test ' echo hola >srcs/bonjour ; cat <srcs/bonjour'
  exec_test ' echo hola > bonjour ; echo que tal >> bonjour ; cat < bonjour'
  exec_test ' echo hola > bonjour ; rm bonjour ; echo que tal >> bonjour ; cat < bonjour'
  exec_test ' e'c'""h""o hola > bonjour ; cat 'bo'""n""jour'
  exec_test ' echo hola > bonjour hey ; ls ; cat bonjour ; cat hey'
  exec_test ' echo hola > srcs/bonjour ; echo hey > srcs/hello ; >srcs/bonjour >srcs/hello <prout ; cat srcs/bonjour srcs/hello'
  exec_test ' echo hola > srcs/bonjour ; echo hey > srcs/hello ; rm srcs/bonjour srcs/hello ; >srcs/bonjour >srcs/hello <prout ; ls srcs ; cat srcs/bonjour srcs/hello'
  exec_test ' echo hola > srcs/bonjour ; echo hey > srcs/hello ; >srcs/bonjour <prout >srcs/hello  ; cat srcs/bonjour  ; cat srcs/hello'
  exec_test ' echo hola > srcs/bonjour ; echo hey > srcs/hello ; rm srcs/bonjour srcs/hello ; >srcs/bonjour <prout >srcs/hello  ; ls srcs ; cat srcs/bonjour'
  exec_test ' echo hola > ../bonjour ; echo hey > ../hello ; >../bonjour >../hello <prout ; cat ../bonjour ../hello'
  exec_test ' echo hola > ../bonjour ; echo hey > ../hello ; rm ../bonjour ../hello ; >../bonjour >../hello <prout ; ls .. ; cat ../bonjour ../hello'
  exec_test ' echo hola > ../bonjour ; echo hey > ../hello ; >../bonjour <prout >../hello  ; cat ../bonjour  ; cat ../hello'
  exec_test ' echo hola > ../bonjour ; echo hey > ../hello ; rm ../bonjour ../hello ; >../bonjour <prout >../hello  ; ls .. ; cat ../bonjour'
  exec_test ' echo hola > srcs/bonjour ; echo hey > srcs/hello ; >srcs/bonjour >>srcs/hello <prout ; cat srcs/bonjour  ; cat srcs/hello'
  exec_test ' echo hola > srcs/bonjour ; echo hey > srcs/hello ; >>srcs/bonjour >srcs/hello <prout ; cat srcs/bonjour  ; cat srcs/hello'
  exec_test ' echo hola > srcs/bonjour ; echo hey > srcs/hello ; >>srcs/bonjour >>srcs/hello <prout ; cat srcs/bonjour  ; cat srcs/hello'
  exec_test ' echo hola > srcs/bonjour ; echo hey > srcs/hello ; >srcs/bonjour <prout >>srcs/hello ; cat srcs/bonjour  ; cat srcs/hello'
  exec_test ' echo hola > srcs/bonjour ; echo hey > srcs/hello ; >>srcs/bonjour <prout >srcs/hello ; cat srcs/bonjour  ; cat srcs/hello'
  exec_test ' echo hola > srcs/bonjour ; echo hey > srcs/hello ; >>srcs/bonjour <prout >>srcs/hello ; cat srcs/bonjour  ; cat srcs/hello'
  exec_test ' echo hola > srcs/bonjour ; echo hey > srcs/hello ; <prout >>srcs/bonjour >>srcs/hello ; cat srcs/bonjour  ; cat srcs/hello'
  exec_test ' echo hola > bonjour ; echo hey > hello ; <bonjour >hello ; cat bonjour  ; cat hello'
  exec_test ' echo hola > bonjour ; echo hey > hello ; >bonjour >hello < prout ; cat bonjour  ; cat hello'
  exec_test ' echo hola > bonjour ; echo hey > hello ; rm bonjour hello ; >bonjour >hello < prout ; cat bonjour  ; cat hello'
  exec_test ' echo hola > bonjour ; echo hey > hello ; >bonjour <prout hello ; cat bonjour  ; cat hello'
  exec_test ' echo hola > bonjour ; echo hey > hello ; rm bonjour hello ; >bonjour <prout hello ; cat bonjour '
  exec_test ' echo hola > bonjour ; <bonjour cat | wc > bonjour ; cat bonjour'
  exec_test ' rm -f bonjour ; rm bonjour > bonjour ; ls -l bonjour'
  exec_test ' export HOLA=""bonjour hello"" ; >$HOLA ; ls'
  exec_test ' export HOLA=""bonjour hello"" ; >""$HOLA"" ; ls'
  exec_test ' export HOLA=""bonjour hello"" ; >$""HOLA"" ; ls'
  exec_test ' export HOLA=""bonjour hello"" ; >$HOLA>hey ; ls'
  exec_test ' export HOLA=""bonjour hello"" ; >hey>$HOLA ; ls'
  exec_test ' export HOLA=""bonjour hello"" ; >hey>$HOLA>hey>hey ; ls'
  exec_test ' export A=hey ; export A B=Hola D E C=""Que Tal"" ; echo $PROUT$B$C > /tmp/a > /tmp/b > /tmp/c ; cat /tmp/a ; cat /tmp/b ; cat /tmp/c"'
  exec_test ' <a cat <b <c'
  exec_test ' <a cat <b <c ; cat a ; cat b ; cat c'
  exec_test ' >a ls >b >>c >d ; cat a ; cat b ; cat c ; cat d'
  exec_test ' >a ls >b >>c >d ; cat a ; cat b ; cat c ; cat d'
  exec_test ' echo hola > a > b > c ; cat a ; cat b ; cat c'
  exec_test ' mkdir dir ; ls -la > dir/bonjour ; cat dir/bonjour'
  exec_test ' <a ; cat a'
  exec_test ' >d cat <a >>e ; cat a ; cat d ; cat e'
  exec_test ' < a > b cat > hey >> d ; cat d ; ls'
  exec_test ' cat << hola'
  exec_test ' cat << 'hola''
  exec_test ' cat << "hola'
  exec_test ' cat << ho"la'
  exec_test ' cat << $HOME'
  exec_test ' cat << hola > bonjour ; cat bonjour'
  exec_test ' cat << hola | rev'
  exec_test ' << hola'
  exec_test ' <<hola'
  exec_test ' cat <<'
  exec_test ' echo hola <<< bonjour'
  exec_test ' echo hola <<<< bonjour'
  exec_test ' echo hola <<<<< bonjour'
  exec_test ' ls *'
  exec_test ' ls *.*'
  exec_test ' ls *.hola'
  exec_test ' cat M*le'
  exec_test ' cat M*ee'
  exec_test ' cat Make*file'
fi

# BONUS
if [ "$1" == "bonus" ] || [ "$1" == "quote" ] || [ "$1" == "wildcard" ] || [ "$1" == "oper" ]; then
  #Compile and set executable rights
  make bonus -C ../ > /dev/null
  cp ../minishell .
  chmod 755 minishell
fi

# BONUS WILDCARD
if [ "$1" == "bonus" ] || [ "$1" == "wildcard" ]; then
  printf $BOLDMAGENTA"\n\tBONUS WILDCARD\n"$RESET
  exec_test "echo * | wc"
  exec_test "echo * | wc ; echo *"
  exec_test "cd ..  ; echo * | wc ; echo *"
  exec_test "echo .* | wc"
  exec_test "cd .. ; echo M*e"
  exec_test "cd .. ; echo M*"
  exec_test "cd .. ; echo *e"
  exec_test "cd .. ; echo *t"
  exec_test "cd .. ; echo *a*e"
  exec_test "cd .. ; echo M*e*e"
  exec_test "cd .. ; echo M*k*f*l*"
  exec_test "cd .. ; echo M*e*ee"
  exec_test "cd .. ; echo *e*e"
  exec_test "echo *.mp3"
  exec_test "mkdir empty ; cd empty ; pwd ; echo * ; cd .. ; rm -rf empty"
fi

# BONUS OPERATOR && || ()
if [ "$1" == "bonus" ] || [ "$1" == "oper" ]; then
  printf $BOLDMAGENTA"\n\tBONUS OPERATOR \$\$ || () \n"$RESET
  exec_test "true && ls"
  exec_test "false&&ls"
  exec_test "true||ls"
  exec_test "false || ls"
  exec_test "true || echo 1 && echo 2"
  exec_test "false || echo 1 && echo 2"
  exec_test "true || (echo 1 && echo 2)"
  exec_test "true || echo 1 && echo 2 || echo 3"
  exec_test "(ls)"
  exec_test "( ls )"
  exec_test "true || (echo 1 && echo 2) || echo 3"
  exec_test "true || (echo 1 && echo 2) && echo 3"
  exec_test "(true || (echo 1 && echo 2) && echo 3)"
  exec_test "true || ((echo 1 && echo 2) && echo 3)"
  exec_test "( )"
  exec_test " ls )"
  exec_test "( ls " 
fi

if [[ "$1" != "" ]] && (( $TOTAL > 0)); then
  PROCENT=$(( $GOOD * 100  / $TOTAL ))
  if (( $PROCENT > 90)); then
    printf $GREEN
  elif (( $PROCENT <= 90 )) && (( $PROCENT > 60 )); then
    printf $YELLOW
  else  
    printf $RED
  fi
  printf "\nPASS: $GOOD / $TOTAL ($PROCENT%%)$RESET\n"
fi

rm -f $pipe lol ls 1 test big_file msh_log leaks pwd test1 tmp1 tmp2 minishell
